"""Per-course quiz specs (one module per course), aggregated into
``QUIZ_REGISTRY`` (slug -> CourseQuiz) for the seed to attach checkpoint and
final quizzes at assembly time. Generated by the academy-quiz-rollout
workflow; one entry per course module in this package."""

from __future__ import annotations

from cyberdyne_backend.application.courses.seed_quizzes import (
    algorithms_advanced as _algorithms_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    algorithms_basics as _algorithms_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    algorithms_intermediate as _algorithms_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import ansible_advanced as _ansible_advanced
from cyberdyne_backend.application.courses.seed_quizzes import ansible_basics as _ansible_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    ansible_intermediate as _ansible_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    blockchain_basics as _blockchain_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    blockchain_beyond_basics as _blockchain_beyond_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import c_basics as _c_basics
from cyberdyne_backend.application.courses.seed_quizzes import c_intermediate as _c_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import control_advanced as _control_advanced
from cyberdyne_backend.application.courses.seed_quizzes import control_basics as _control_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    control_intermediate as _control_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import cpp_basics as _cpp_basics
from cyberdyne_backend.application.courses.seed_quizzes import cpp_intermediate as _cpp_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import csharp_advanced as _csharp_advanced
from cyberdyne_backend.application.courses.seed_quizzes import csharp_basics as _csharp_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    csharp_intermediate as _csharp_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import docker_advanced as _docker_advanced
from cyberdyne_backend.application.courses.seed_quizzes import docker_basics as _docker_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    docker_intermediate as _docker_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import go_basics as _go_basics
from cyberdyne_backend.application.courses.seed_quizzes import go_intermediate as _go_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import (
    javascript_basics as _javascript_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    javascript_intermediate as _javascript_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    kubernetes_advanced as _kubernetes_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    kubernetes_basics as _kubernetes_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    kubernetes_intermediate as _kubernetes_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import math_advanced as _math_advanced
from cyberdyne_backend.application.courses.seed_quizzes import math_basics as _math_basics
from cyberdyne_backend.application.courses.seed_quizzes import math_complex as _math_complex
from cyberdyne_backend.application.courses.seed_quizzes import math_discrete as _math_discrete
from cyberdyne_backend.application.courses.seed_quizzes import math_fourier as _math_fourier
from cyberdyne_backend.application.courses.seed_quizzes import math_information as _math_information
from cyberdyne_backend.application.courses.seed_quizzes import (
    math_intermediate as _math_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import math_matrices as _math_matrices
from cyberdyne_backend.application.courses.seed_quizzes import math_numerical as _math_numerical
from cyberdyne_backend.application.courses.seed_quizzes import (
    math_optimization as _math_optimization,
)
from cyberdyne_backend.application.courses.seed_quizzes import math_probability as _math_probability
from cyberdyne_backend.application.courses.seed_quizzes import matlab_basics as _matlab_basics
from cyberdyne_backend.application.courses.seed_quizzes import mongodb as _mongodb
from cyberdyne_backend.application.courses.seed_quizzes import physics_basics as _physics_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    physics_intermediate as _physics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    physics_quadrotor_dynamics as _physics_quadrotor_dynamics,
)
from cyberdyne_backend.application.courses.seed_quizzes import postgresql as _postgresql
from cyberdyne_backend.application.courses.seed_quizzes import python_course as _python_course
from cyberdyne_backend.application.courses.seed_quizzes import (
    robotics_advanced as _robotics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import robotics_basics as _robotics_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    robotics_intermediate as _robotics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import rust_basics as _rust_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    rust_intermediate as _rust_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import signals_advanced as _signals_advanced
from cyberdyne_backend.application.courses.seed_quizzes import signals_basics as _signals_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    signals_intermediate as _signals_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import sql_basics as _sql_basics
from cyberdyne_backend.application.courses.seed_quizzes import sql_intermediate as _sql_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import statinf_advanced as _statinf_advanced
from cyberdyne_backend.application.courses.seed_quizzes import statinf_basics as _statinf_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    statinf_intermediate as _statinf_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import swift_basics as _swift_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    swift_intermediate as _swift_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    terraform_advanced as _terraform_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import terraform_basics as _terraform_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    terraform_intermediate as _terraform_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    typescript_basics as _typescript_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    typescript_intermediate as _typescript_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    vectorcalc_advanced as _vectorcalc_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    vectorcalc_basics as _vectorcalc_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    vectorcalc_intermediate as _vectorcalc_intermediate,
)
from cyberdyne_backend.application.courses.seed_types import CourseQuiz

QUIZ_REGISTRY: dict[str, CourseQuiz] = {
    "algorithms-advanced": _algorithms_advanced.QUIZ,
    "algorithms-basics": _algorithms_basics.QUIZ,
    "algorithms-intermediate": _algorithms_intermediate.QUIZ,
    "ansible-advanced": _ansible_advanced.QUIZ,
    "ansible-basics": _ansible_basics.QUIZ,
    "ansible-intermediate": _ansible_intermediate.QUIZ,
    "blockchain-basics": _blockchain_basics.QUIZ,
    "blockchain-beyond-basics": _blockchain_beyond_basics.QUIZ,
    "c-basics": _c_basics.QUIZ,
    "c-intermediate": _c_intermediate.QUIZ,
    "control-advanced": _control_advanced.QUIZ,
    "control-basics": _control_basics.QUIZ,
    "control-intermediate": _control_intermediate.QUIZ,
    "cpp-basics": _cpp_basics.QUIZ,
    "cpp-intermediate": _cpp_intermediate.QUIZ,
    "csharp-advanced": _csharp_advanced.QUIZ,
    "csharp-basics": _csharp_basics.QUIZ,
    "csharp-intermediate": _csharp_intermediate.QUIZ,
    "docker-advanced": _docker_advanced.QUIZ,
    "docker-basics": _docker_basics.QUIZ,
    "docker-intermediate": _docker_intermediate.QUIZ,
    "go-basics": _go_basics.QUIZ,
    "go-intermediate": _go_intermediate.QUIZ,
    "javascript-basics": _javascript_basics.QUIZ,
    "javascript-intermediate": _javascript_intermediate.QUIZ,
    "kubernetes-advanced": _kubernetes_advanced.QUIZ,
    "kubernetes-basics": _kubernetes_basics.QUIZ,
    "kubernetes-intermediate": _kubernetes_intermediate.QUIZ,
    "math-advanced": _math_advanced.QUIZ,
    "math-basics": _math_basics.QUIZ,
    "math-complex": _math_complex.QUIZ,
    "math-discrete": _math_discrete.QUIZ,
    "math-fourier": _math_fourier.QUIZ,
    "math-information": _math_information.QUIZ,
    "math-intermediate": _math_intermediate.QUIZ,
    "math-matrices": _math_matrices.QUIZ,
    "math-numerical": _math_numerical.QUIZ,
    "math-optimization": _math_optimization.QUIZ,
    "math-probability": _math_probability.QUIZ,
    "matlab-basics": _matlab_basics.QUIZ,
    "mongodb": _mongodb.QUIZ,
    "physics-basics": _physics_basics.QUIZ,
    "physics-intermediate": _physics_intermediate.QUIZ,
    "physics-quadrotor-dynamics": _physics_quadrotor_dynamics.QUIZ,
    "postgresql": _postgresql.QUIZ,
    "python-course": _python_course.QUIZ,
    "robotics-advanced": _robotics_advanced.QUIZ,
    "robotics-basics": _robotics_basics.QUIZ,
    "robotics-intermediate": _robotics_intermediate.QUIZ,
    "rust-basics": _rust_basics.QUIZ,
    "rust-intermediate": _rust_intermediate.QUIZ,
    "signals-advanced": _signals_advanced.QUIZ,
    "signals-basics": _signals_basics.QUIZ,
    "signals-intermediate": _signals_intermediate.QUIZ,
    "sql-basics": _sql_basics.QUIZ,
    "sql-intermediate": _sql_intermediate.QUIZ,
    "statinf-advanced": _statinf_advanced.QUIZ,
    "statinf-basics": _statinf_basics.QUIZ,
    "statinf-intermediate": _statinf_intermediate.QUIZ,
    "swift-basics": _swift_basics.QUIZ,
    "swift-intermediate": _swift_intermediate.QUIZ,
    "terraform-advanced": _terraform_advanced.QUIZ,
    "terraform-basics": _terraform_basics.QUIZ,
    "terraform-intermediate": _terraform_intermediate.QUIZ,
    "typescript-basics": _typescript_basics.QUIZ,
    "typescript-intermediate": _typescript_intermediate.QUIZ,
    "vectorcalc-advanced": _vectorcalc_advanced.QUIZ,
    "vectorcalc-basics": _vectorcalc_basics.QUIZ,
    "vectorcalc-intermediate": _vectorcalc_intermediate.QUIZ,
}

__all__ = ["QUIZ_REGISTRY"]
