"""Per-course quiz specs (one module per course), aggregated into
``QUIZ_REGISTRY`` (slug -> CourseQuiz) for the seed to attach checkpoint and
final quizzes at assembly time. Generated by the academy-quiz-rollout
workflow; one entry per course module in this package."""

from __future__ import annotations

from cyberdyne_backend.application.courses.seed_quizzes import (
    algorithms_advanced as _algorithms_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    algorithms_basics as _algorithms_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    algorithms_intermediate as _algorithms_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    algorithms_logic_computing as _algorithms_logic_computing,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    analog_ic_advanced as _analog_ic_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import analog_ic_basics as _analog_ic_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    analog_ic_intermediate as _analog_ic_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import ansible_advanced as _ansible_advanced
from cyberdyne_backend.application.courses.seed_quizzes import ansible_basics as _ansible_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    ansible_intermediate as _ansible_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import battery_advanced as _battery_advanced
from cyberdyne_backend.application.courses.seed_quizzes import battery_basics as _battery_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    battery_intermediate as _battery_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    blockchain_basics as _blockchain_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    blockchain_beyond_basics as _blockchain_beyond_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import c_basics as _c_basics
from cyberdyne_backend.application.courses.seed_quizzes import c_intermediate as _c_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import (
    comparch_advanced as _comparch_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import comparch_basics as _comparch_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    comparch_intermediate as _comparch_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    computational_thinking_advanced as _computational_thinking_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    computational_thinking_basics as _computational_thinking_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    computational_thinking_intermediate as _computational_thinking_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import control_advanced as _control_advanced
from cyberdyne_backend.application.courses.seed_quizzes import control_basics as _control_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    control_intermediate as _control_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import cpp_basics as _cpp_basics
from cyberdyne_backend.application.courses.seed_quizzes import cpp_intermediate as _cpp_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import csharp_advanced as _csharp_advanced
from cyberdyne_backend.application.courses.seed_quizzes import csharp_basics as _csharp_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    csharp_intermediate as _csharp_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    digital_comms_advanced as _digital_comms_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    digital_comms_basics as _digital_comms_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    digital_comms_intermediate as _digital_comms_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    digital_logic_advanced as _digital_logic_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    digital_logic_basics as _digital_logic_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    digital_logic_intermediate as _digital_logic_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import django_advanced as _django_advanced
from cyberdyne_backend.application.courses.seed_quizzes import django_basics as _django_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    django_intermediate as _django_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import docker_advanced as _docker_advanced
from cyberdyne_backend.application.courses.seed_quizzes import docker_basics as _docker_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    docker_intermediate as _docker_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import dsp_advanced as _dsp_advanced
from cyberdyne_backend.application.courses.seed_quizzes import dsp_basics as _dsp_basics
from cyberdyne_backend.application.courses.seed_quizzes import dsp_intermediate as _dsp_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import (
    electromagnetics_advanced as _electromagnetics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electromagnetics_basics as _electromagnetics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electromagnetics_intermediate as _electromagnetics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electronics_advanced as _electronics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electronics_basics as _electronics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electronics_intermediate as _electronics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    embedded_advanced as _embedded_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import embedded_basics as _embedded_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    embedded_intermediate as _embedded_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    english_brazil_advanced as _english_brazil_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    english_brazil_basics as _english_brazil_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    english_brazil_intermediate as _english_brazil_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import fpga_advanced as _fpga_advanced
from cyberdyne_backend.application.courses.seed_quizzes import fpga_basics as _fpga_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    fpga_intermediate as _fpga_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import go_basics as _go_basics
from cyberdyne_backend.application.courses.seed_quizzes import go_intermediate as _go_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import (
    javascript_basics as _javascript_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    javascript_intermediate as _javascript_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    kubernetes_advanced as _kubernetes_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    kubernetes_basics as _kubernetes_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    kubernetes_intermediate as _kubernetes_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    machines_advanced as _machines_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import machines_basics as _machines_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    machines_intermediate as _machines_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import math_advanced as _math_advanced
from cyberdyne_backend.application.courses.seed_quizzes import math_basics as _math_basics
from cyberdyne_backend.application.courses.seed_quizzes import math_complex as _math_complex
from cyberdyne_backend.application.courses.seed_quizzes import math_discrete as _math_discrete
from cyberdyne_backend.application.courses.seed_quizzes import math_fourier as _math_fourier
from cyberdyne_backend.application.courses.seed_quizzes import math_information as _math_information
from cyberdyne_backend.application.courses.seed_quizzes import (
    math_intermediate as _math_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import math_matrices as _math_matrices
from cyberdyne_backend.application.courses.seed_quizzes import math_numerical as _math_numerical
from cyberdyne_backend.application.courses.seed_quizzes import (
    math_optimization as _math_optimization,
)
from cyberdyne_backend.application.courses.seed_quizzes import math_probability as _math_probability
from cyberdyne_backend.application.courses.seed_quizzes import matlab_basics as _matlab_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    microwave_advanced as _microwave_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import microwave_basics as _microwave_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    microwave_intermediate as _microwave_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import mongodb as _mongodb
from cyberdyne_backend.application.courses.seed_quizzes import pcb_advanced as _pcb_advanced
from cyberdyne_backend.application.courses.seed_quizzes import pcb_basics as _pcb_basics
from cyberdyne_backend.application.courses.seed_quizzes import pcb_intermediate as _pcb_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import (
    photonics_advanced as _photonics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import photonics_basics as _photonics_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    photonics_intermediate as _photonics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import physics_basics as _physics_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    physics_intermediate as _physics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    physics_quadrotor_dynamics as _physics_quadrotor_dynamics,
)
from cyberdyne_backend.application.courses.seed_quizzes import postgresql as _postgresql
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_electronics_advanced as _power_electronics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_electronics_basics as _power_electronics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_electronics_intermediate as _power_electronics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_systems_advanced as _power_systems_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_systems_basics as _power_systems_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_systems_intermediate as _power_systems_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import python_course as _python_course
from cyberdyne_backend.application.courses.seed_quizzes import rails_advanced as _rails_advanced
from cyberdyne_backend.application.courses.seed_quizzes import rails_basics as _rails_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    rails_intermediate as _rails_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    rf_comms_advanced as _rf_comms_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import rf_comms_basics as _rf_comms_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    rf_comms_intermediate as _rf_comms_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    robotics_advanced as _robotics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import robotics_basics as _robotics_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    robotics_intermediate as _robotics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import rust_basics as _rust_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    rust_intermediate as _rust_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    semiconductor_advanced as _semiconductor_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    semiconductor_basics as _semiconductor_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    semiconductor_intermediate as _semiconductor_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import sensors_advanced as _sensors_advanced
from cyberdyne_backend.application.courses.seed_quizzes import sensors_basics as _sensors_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    sensors_intermediate as _sensors_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import signals_advanced as _signals_advanced
from cyberdyne_backend.application.courses.seed_quizzes import signals_basics as _signals_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    signals_intermediate as _signals_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    software_architecture_advanced as _software_architecture_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    software_architecture_basics as _software_architecture_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    software_architecture_intermediate as _software_architecture_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    software_quality_advanced as _software_quality_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    software_quality_basics as _software_quality_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    software_quality_intermediate as _software_quality_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import sql_basics as _sql_basics
from cyberdyne_backend.application.courses.seed_quizzes import sql_intermediate as _sql_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import statinf_advanced as _statinf_advanced
from cyberdyne_backend.application.courses.seed_quizzes import statinf_basics as _statinf_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    statinf_intermediate as _statinf_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import swift_basics as _swift_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    swift_intermediate as _swift_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    sysverilog_advanced as _sysverilog_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    sysverilog_basics as _sysverilog_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    sysverilog_intermediate as _sysverilog_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    technical_english_advanced as _technical_english_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    technical_english_basics as _technical_english_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    technical_english_intermediate as _technical_english_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    terraform_advanced as _terraform_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import terraform_basics as _terraform_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    terraform_intermediate as _terraform_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    typescript_basics as _typescript_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    typescript_intermediate as _typescript_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    vectorcalc_advanced as _vectorcalc_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    vectorcalc_basics as _vectorcalc_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    vectorcalc_intermediate as _vectorcalc_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import vlsi_advanced as _vlsi_advanced
from cyberdyne_backend.application.courses.seed_quizzes import vlsi_basics as _vlsi_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    vlsi_intermediate as _vlsi_intermediate,
)
from cyberdyne_backend.application.courses.seed_types import CourseQuiz

QUIZ_REGISTRY: dict[str, CourseQuiz] = {
    "algorithms-advanced": _algorithms_advanced.QUIZ,
    "algorithms-basics": _algorithms_basics.QUIZ,
    "algorithms-intermediate": _algorithms_intermediate.QUIZ,
    "algorithms-logic-computing": _algorithms_logic_computing.QUIZ,
    "analog-ic-advanced": _analog_ic_advanced.QUIZ,
    "analog-ic-basics": _analog_ic_basics.QUIZ,
    "analog-ic-intermediate": _analog_ic_intermediate.QUIZ,
    "ansible-advanced": _ansible_advanced.QUIZ,
    "ansible-basics": _ansible_basics.QUIZ,
    "ansible-intermediate": _ansible_intermediate.QUIZ,
    "battery-advanced": _battery_advanced.QUIZ,
    "battery-basics": _battery_basics.QUIZ,
    "battery-intermediate": _battery_intermediate.QUIZ,
    "blockchain-basics": _blockchain_basics.QUIZ,
    "blockchain-beyond-basics": _blockchain_beyond_basics.QUIZ,
    "c-basics": _c_basics.QUIZ,
    "c-intermediate": _c_intermediate.QUIZ,
    "comparch-advanced": _comparch_advanced.QUIZ,
    "comparch-basics": _comparch_basics.QUIZ,
    "comparch-intermediate": _comparch_intermediate.QUIZ,
    "computational-thinking-advanced": _computational_thinking_advanced.QUIZ,
    "computational-thinking-basics": _computational_thinking_basics.QUIZ,
    "computational-thinking-intermediate": _computational_thinking_intermediate.QUIZ,
    "control-advanced": _control_advanced.QUIZ,
    "control-basics": _control_basics.QUIZ,
    "control-intermediate": _control_intermediate.QUIZ,
    "cpp-basics": _cpp_basics.QUIZ,
    "cpp-intermediate": _cpp_intermediate.QUIZ,
    "csharp-advanced": _csharp_advanced.QUIZ,
    "csharp-basics": _csharp_basics.QUIZ,
    "csharp-intermediate": _csharp_intermediate.QUIZ,
    "digital-comms-advanced": _digital_comms_advanced.QUIZ,
    "digital-comms-basics": _digital_comms_basics.QUIZ,
    "digital-comms-intermediate": _digital_comms_intermediate.QUIZ,
    "digital-logic-advanced": _digital_logic_advanced.QUIZ,
    "digital-logic-basics": _digital_logic_basics.QUIZ,
    "digital-logic-intermediate": _digital_logic_intermediate.QUIZ,
    "django-advanced": _django_advanced.QUIZ,
    "django-basics": _django_basics.QUIZ,
    "django-intermediate": _django_intermediate.QUIZ,
    "docker-advanced": _docker_advanced.QUIZ,
    "docker-basics": _docker_basics.QUIZ,
    "docker-intermediate": _docker_intermediate.QUIZ,
    "dsp-advanced": _dsp_advanced.QUIZ,
    "dsp-basics": _dsp_basics.QUIZ,
    "dsp-intermediate": _dsp_intermediate.QUIZ,
    "electromagnetics-advanced": _electromagnetics_advanced.QUIZ,
    "electromagnetics-basics": _electromagnetics_basics.QUIZ,
    "electromagnetics-intermediate": _electromagnetics_intermediate.QUIZ,
    "electronics-advanced": _electronics_advanced.QUIZ,
    "electronics-basics": _electronics_basics.QUIZ,
    "electronics-intermediate": _electronics_intermediate.QUIZ,
    "embedded-advanced": _embedded_advanced.QUIZ,
    "embedded-basics": _embedded_basics.QUIZ,
    "embedded-intermediate": _embedded_intermediate.QUIZ,
    "english-br-advanced": _english_brazil_advanced.QUIZ,
    "english-br-basics": _english_brazil_basics.QUIZ,
    "english-br-intermediate": _english_brazil_intermediate.QUIZ,
    "fpga-advanced": _fpga_advanced.QUIZ,
    "fpga-basics": _fpga_basics.QUIZ,
    "fpga-intermediate": _fpga_intermediate.QUIZ,
    "go-basics": _go_basics.QUIZ,
    "go-intermediate": _go_intermediate.QUIZ,
    "javascript-basics": _javascript_basics.QUIZ,
    "javascript-intermediate": _javascript_intermediate.QUIZ,
    "kubernetes-advanced": _kubernetes_advanced.QUIZ,
    "kubernetes-basics": _kubernetes_basics.QUIZ,
    "kubernetes-intermediate": _kubernetes_intermediate.QUIZ,
    "machines-advanced": _machines_advanced.QUIZ,
    "machines-basics": _machines_basics.QUIZ,
    "machines-intermediate": _machines_intermediate.QUIZ,
    "math-advanced": _math_advanced.QUIZ,
    "math-basics": _math_basics.QUIZ,
    "math-complex": _math_complex.QUIZ,
    "math-discrete": _math_discrete.QUIZ,
    "math-fourier": _math_fourier.QUIZ,
    "math-information": _math_information.QUIZ,
    "math-intermediate": _math_intermediate.QUIZ,
    "math-matrices": _math_matrices.QUIZ,
    "math-numerical": _math_numerical.QUIZ,
    "math-optimization": _math_optimization.QUIZ,
    "math-probability": _math_probability.QUIZ,
    "matlab-basics": _matlab_basics.QUIZ,
    "microwave-advanced": _microwave_advanced.QUIZ,
    "microwave-basics": _microwave_basics.QUIZ,
    "microwave-intermediate": _microwave_intermediate.QUIZ,
    "mongodb": _mongodb.QUIZ,
    "pcb-advanced": _pcb_advanced.QUIZ,
    "pcb-basics": _pcb_basics.QUIZ,
    "pcb-intermediate": _pcb_intermediate.QUIZ,
    "photonics-advanced": _photonics_advanced.QUIZ,
    "photonics-basics": _photonics_basics.QUIZ,
    "photonics-intermediate": _photonics_intermediate.QUIZ,
    "physics-basics": _physics_basics.QUIZ,
    "physics-intermediate": _physics_intermediate.QUIZ,
    "physics-quadrotor-dynamics": _physics_quadrotor_dynamics.QUIZ,
    "postgresql": _postgresql.QUIZ,
    "power-electronics-advanced": _power_electronics_advanced.QUIZ,
    "power-electronics-basics": _power_electronics_basics.QUIZ,
    "power-electronics-intermediate": _power_electronics_intermediate.QUIZ,
    "power-systems-advanced": _power_systems_advanced.QUIZ,
    "power-systems-basics": _power_systems_basics.QUIZ,
    "power-systems-intermediate": _power_systems_intermediate.QUIZ,
    "python-course": _python_course.QUIZ,
    "rails-advanced": _rails_advanced.QUIZ,
    "rails-basics": _rails_basics.QUIZ,
    "rails-intermediate": _rails_intermediate.QUIZ,
    "rf-comms-advanced": _rf_comms_advanced.QUIZ,
    "rf-comms-basics": _rf_comms_basics.QUIZ,
    "rf-comms-intermediate": _rf_comms_intermediate.QUIZ,
    "robotics-advanced": _robotics_advanced.QUIZ,
    "robotics-basics": _robotics_basics.QUIZ,
    "robotics-intermediate": _robotics_intermediate.QUIZ,
    "rust-basics": _rust_basics.QUIZ,
    "rust-intermediate": _rust_intermediate.QUIZ,
    "semiconductor-advanced": _semiconductor_advanced.QUIZ,
    "semiconductor-basics": _semiconductor_basics.QUIZ,
    "semiconductor-intermediate": _semiconductor_intermediate.QUIZ,
    "sensors-advanced": _sensors_advanced.QUIZ,
    "sensors-basics": _sensors_basics.QUIZ,
    "sensors-intermediate": _sensors_intermediate.QUIZ,
    "signals-advanced": _signals_advanced.QUIZ,
    "signals-basics": _signals_basics.QUIZ,
    "signals-intermediate": _signals_intermediate.QUIZ,
    "software-architecture-advanced": _software_architecture_advanced.QUIZ,
    "software-architecture-basics": _software_architecture_basics.QUIZ,
    "software-architecture-intermediate": _software_architecture_intermediate.QUIZ,
    "software-quality-advanced": _software_quality_advanced.QUIZ,
    "software-quality-basics": _software_quality_basics.QUIZ,
    "software-quality-intermediate": _software_quality_intermediate.QUIZ,
    "sql-basics": _sql_basics.QUIZ,
    "sql-intermediate": _sql_intermediate.QUIZ,
    "statinf-advanced": _statinf_advanced.QUIZ,
    "statinf-basics": _statinf_basics.QUIZ,
    "statinf-intermediate": _statinf_intermediate.QUIZ,
    "swift-basics": _swift_basics.QUIZ,
    "swift-intermediate": _swift_intermediate.QUIZ,
    "sysverilog-advanced": _sysverilog_advanced.QUIZ,
    "sysverilog-basics": _sysverilog_basics.QUIZ,
    "sysverilog-intermediate": _sysverilog_intermediate.QUIZ,
    "technical-english-advanced": _technical_english_advanced.QUIZ,
    "technical-english-basics": _technical_english_basics.QUIZ,
    "technical-english-intermediate": _technical_english_intermediate.QUIZ,
    "terraform-advanced": _terraform_advanced.QUIZ,
    "terraform-basics": _terraform_basics.QUIZ,
    "terraform-intermediate": _terraform_intermediate.QUIZ,
    "typescript-basics": _typescript_basics.QUIZ,
    "typescript-intermediate": _typescript_intermediate.QUIZ,
    "vectorcalc-advanced": _vectorcalc_advanced.QUIZ,
    "vectorcalc-basics": _vectorcalc_basics.QUIZ,
    "vectorcalc-intermediate": _vectorcalc_intermediate.QUIZ,
    "vlsi-advanced": _vlsi_advanced.QUIZ,
    "vlsi-basics": _vlsi_basics.QUIZ,
    "vlsi-intermediate": _vlsi_intermediate.QUIZ,
}

__all__ = ["QUIZ_REGISTRY"]
