"""Per-course quiz specs (one module per course), aggregated into
``QUIZ_REGISTRY`` (slug -> CourseQuiz) for the seed to attach checkpoint and
final quizzes at assembly time. Generated by the academy-quiz-rollout
workflow; one entry per course module in this package."""

from __future__ import annotations

from cyberdyne_backend.application.courses.seed_quizzes import (
    actuators_motion_systems_advanced as _actuators_motion_systems_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    actuators_motion_systems_basics as _actuators_motion_systems_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    actuators_motion_systems_intermediate as _actuators_motion_systems_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    adaptive_dsp_advanced as _adaptive_dsp_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    adaptive_dsp_basics as _adaptive_dsp_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    adaptive_dsp_intermediate as _adaptive_dsp_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    additive_manufacturing_advanced as _additive_manufacturing_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    additive_manufacturing_basics as _additive_manufacturing_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    additive_manufacturing_intermediate as _additive_manufacturing_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    admet_prediction_advanced as _admet_prediction_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    admet_prediction_basics as _admet_prediction_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    admet_prediction_intermediate as _admet_prediction_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    advanced_control_advanced as _advanced_control_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    advanced_control_basics as _advanced_control_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    advanced_control_intermediate as _advanced_control_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ai_drug_discovery_advanced as _ai_drug_discovery_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ai_drug_discovery_basics as _ai_drug_discovery_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ai_drug_discovery_intermediate as _ai_drug_discovery_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ai_organic_shapes_advanced as _ai_organic_shapes_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ai_organic_shapes_basics as _ai_organic_shapes_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ai_organic_shapes_intermediate as _ai_organic_shapes_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    algorithms_advanced as _algorithms_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    algorithms_basics as _algorithms_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    algorithms_intermediate as _algorithms_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    algorithms_logic_computing as _algorithms_logic_computing,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    analog_comms_advanced as _analog_comms_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    analog_comms_basics as _analog_comms_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    analog_comms_intermediate as _analog_comms_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    analog_ic_advanced as _analog_ic_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import analog_ic_basics as _analog_ic_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    analog_ic_intermediate as _analog_ic_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    analytical_chemistry_advanced as _analytical_chemistry_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    analytical_chemistry_basics as _analytical_chemistry_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    analytical_chemistry_intermediate as _analytical_chemistry_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import ansible_advanced as _ansible_advanced
from cyberdyne_backend.application.courses.seed_quizzes import ansible_basics as _ansible_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    ansible_intermediate as _ansible_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    audio_processing_advanced as _audio_processing_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    audio_processing_basics as _audio_processing_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    audio_processing_intermediate as _audio_processing_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import battery_advanced as _battery_advanced
from cyberdyne_backend.application.courses.seed_quizzes import battery_basics as _battery_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    battery_intermediate as _battery_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    bio_databases_advanced as _bio_databases_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    bio_databases_basics as _bio_databases_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    bio_databases_intermediate as _bio_databases_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    biochemistry_advanced as _biochemistry_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    biochemistry_basics as _biochemistry_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    biochemistry_intermediate as _biochemistry_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    bioinformatics_advanced as _bioinformatics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    bioinformatics_basics as _bioinformatics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    bioinformatics_intermediate as _bioinformatics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    biostatistics_advanced as _biostatistics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    biostatistics_basics as _biostatistics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    biostatistics_intermediate as _biostatistics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    blockchain_basics as _blockchain_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    blockchain_beyond_basics as _blockchain_beyond_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import c_basics as _c_basics
from cyberdyne_backend.application.courses.seed_quizzes import c_intermediate as _c_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import (
    cad_cae_parametric_advanced as _cad_cae_parametric_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    cad_cae_parametric_basics as _cad_cae_parametric_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    cad_cae_parametric_intermediate as _cad_cae_parametric_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    capstone_ai_drug_design_advanced as _capstone_ai_drug_design_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    capstone_ai_drug_design_basics as _capstone_ai_drug_design_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    capstone_ai_drug_design_intermediate as _capstone_ai_drug_design_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    capstone_generative_mechanical_design_advanced as _capstone_generative_mechanical_design_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    capstone_generative_mechanical_design_basics as _capstone_generative_mechanical_design_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    capstone_generative_mechanical_design_intermediate as _capstone_generative_mechanical_design_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    cell_biology_advanced as _cell_biology_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    cell_biology_basics as _cell_biology_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    cell_biology_intermediate as _cell_biology_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    cheminformatics_advanced as _cheminformatics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    cheminformatics_basics as _cheminformatics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    cheminformatics_intermediate as _cheminformatics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    circuit_analysis_advanced as _circuit_analysis_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    circuit_analysis_basics as _circuit_analysis_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    circuit_analysis_intermediate as _circuit_analysis_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    coding_theory_advanced as _coding_theory_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    coding_theory_basics as _coding_theory_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    coding_theory_intermediate as _coding_theory_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    comparch_advanced as _comparch_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import comparch_basics as _comparch_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    comparch_intermediate as _comparch_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    computational_fluid_dynamics_advanced as _computational_fluid_dynamics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    computational_fluid_dynamics_basics as _computational_fluid_dynamics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    computational_fluid_dynamics_intermediate as _computational_fluid_dynamics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    computational_thinking_advanced as _computational_thinking_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    computational_thinking_basics as _computational_thinking_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    computational_thinking_intermediate as _computational_thinking_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    computer_aided_drug_design_advanced as _computer_aided_drug_design_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    computer_aided_drug_design_basics as _computer_aided_drug_design_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    computer_aided_drug_design_intermediate as _computer_aided_drug_design_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import control_advanced as _control_advanced
from cyberdyne_backend.application.courses.seed_quizzes import control_basics as _control_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    control_intermediate as _control_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import cpp_basics as _cpp_basics
from cyberdyne_backend.application.courses.seed_quizzes import cpp_intermediate as _cpp_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import csharp_advanced as _csharp_advanced
from cyberdyne_backend.application.courses.seed_quizzes import csharp_basics as _csharp_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    csharp_intermediate as _csharp_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    data_converters_advanced as _data_converters_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    data_converters_basics as _data_converters_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    data_converters_intermediate as _data_converters_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    data_visualization_bio_advanced as _data_visualization_bio_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    data_visualization_bio_basics as _data_visualization_bio_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    data_visualization_bio_intermediate as _data_visualization_bio_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    deep_learning_biology_advanced as _deep_learning_biology_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    deep_learning_biology_basics as _deep_learning_biology_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    deep_learning_biology_intermediate as _deep_learning_biology_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    design_optimization_advanced as _design_optimization_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    design_optimization_basics as _design_optimization_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    design_optimization_intermediate as _design_optimization_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    digital_comms_advanced as _digital_comms_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    digital_comms_basics as _digital_comms_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    digital_comms_intermediate as _digital_comms_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    digital_logic_advanced as _digital_logic_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    digital_logic_basics as _digital_logic_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    digital_logic_intermediate as _digital_logic_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import django_advanced as _django_advanced
from cyberdyne_backend.application.courses.seed_quizzes import django_basics as _django_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    django_intermediate as _django_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import docker_advanced as _docker_advanced
from cyberdyne_backend.application.courses.seed_quizzes import docker_basics as _docker_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    docker_intermediate as _docker_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    docking_virtual_screening_advanced as _docking_virtual_screening_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    docking_virtual_screening_basics as _docking_virtual_screening_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    docking_virtual_screening_intermediate as _docking_virtual_screening_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    drug_development_regulatory_advanced as _drug_development_regulatory_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    drug_development_regulatory_basics as _drug_development_regulatory_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    drug_development_regulatory_intermediate as _drug_development_regulatory_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import dsp_advanced as _dsp_advanced
from cyberdyne_backend.application.courses.seed_quizzes import dsp_basics as _dsp_basics
from cyberdyne_backend.application.courses.seed_quizzes import dsp_intermediate as _dsp_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import (
    electric_drives_advanced as _electric_drives_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electric_drives_basics as _electric_drives_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electric_drives_intermediate as _electric_drives_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electromagnetics_advanced as _electromagnetics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electromagnetics_basics as _electromagnetics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electromagnetics_intermediate as _electromagnetics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electronics_advanced as _electronics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electronics_basics as _electronics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    electronics_intermediate as _electronics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    embedded_advanced as _embedded_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import embedded_basics as _embedded_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    embedded_intermediate as _embedded_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    engineering_dynamics_advanced as _engineering_dynamics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    engineering_dynamics_basics as _engineering_dynamics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    engineering_dynamics_intermediate as _engineering_dynamics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    engineering_graphics_cad_advanced as _engineering_graphics_cad_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    engineering_graphics_cad_basics as _engineering_graphics_cad_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    engineering_graphics_cad_intermediate as _engineering_graphics_cad_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    engineering_statics_advanced as _engineering_statics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    engineering_statics_basics as _engineering_statics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    engineering_statics_intermediate as _engineering_statics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    engineering_thermodynamics_advanced as _engineering_thermodynamics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    engineering_thermodynamics_basics as _engineering_thermodynamics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    engineering_thermodynamics_intermediate as _engineering_thermodynamics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    english_brazil_advanced as _english_brazil_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    english_brazil_basics as _english_brazil_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    english_brazil_intermediate as _english_brazil_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    evolution_ecology_advanced as _evolution_ecology_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    evolution_ecology_basics as _evolution_ecology_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    evolution_ecology_intermediate as _evolution_ecology_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    fiber_optics_advanced as _fiber_optics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    fiber_optics_basics as _fiber_optics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    fiber_optics_intermediate as _fiber_optics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    filter_design_advanced as _filter_design_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    filter_design_basics as _filter_design_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    filter_design_intermediate as _filter_design_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    finite_element_analysis_advanced as _finite_element_analysis_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    finite_element_analysis_basics as _finite_element_analysis_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    finite_element_analysis_intermediate as _finite_element_analysis_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    fluid_mechanics_advanced as _fluid_mechanics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    fluid_mechanics_basics as _fluid_mechanics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    fluid_mechanics_intermediate as _fluid_mechanics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import fpga_advanced as _fpga_advanced
from cyberdyne_backend.application.courses.seed_quizzes import fpga_basics as _fpga_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    fpga_intermediate as _fpga_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    general_chemistry_advanced as _general_chemistry_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    general_chemistry_basics as _general_chemistry_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    general_chemistry_intermediate as _general_chemistry_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    generative_design_advanced as _generative_design_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    generative_design_basics as _generative_design_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    generative_design_intermediate as _generative_design_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    generative_molecular_design_advanced as _generative_molecular_design_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    generative_molecular_design_basics as _generative_molecular_design_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    generative_molecular_design_intermediate as _generative_molecular_design_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    genetics_advanced as _genetics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import genetics_basics as _genetics_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    genetics_intermediate as _genetics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    genomics_advanced as _genomics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import genomics_basics as _genomics_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    genomics_intermediate as _genomics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import go_basics as _go_basics
from cyberdyne_backend.application.courses.seed_quizzes import go_intermediate as _go_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import (
    heat_transfer_advanced as _heat_transfer_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    heat_transfer_basics as _heat_transfer_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    heat_transfer_intermediate as _heat_transfer_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    high_voltage_advanced as _high_voltage_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    high_voltage_basics as _high_voltage_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    high_voltage_intermediate as _high_voltage_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    hydraulics_pneumatics_advanced as _hydraulics_pneumatics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    hydraulics_pneumatics_basics as _hydraulics_pneumatics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    hydraulics_pneumatics_intermediate as _hydraulics_pneumatics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    image_processing_advanced as _image_processing_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    image_processing_basics as _image_processing_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    image_processing_intermediate as _image_processing_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    immunology_advanced as _immunology_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    immunology_basics as _immunology_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    immunology_intermediate as _immunology_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    javascript_basics as _javascript_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    javascript_intermediate as _javascript_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    kinematics_of_machinery_advanced as _kinematics_of_machinery_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    kinematics_of_machinery_basics as _kinematics_of_machinery_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    kinematics_of_machinery_intermediate as _kinematics_of_machinery_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    kubernetes_advanced as _kubernetes_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    kubernetes_basics as _kubernetes_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    kubernetes_intermediate as _kubernetes_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    machine_design_advanced as _machine_design_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    machine_design_basics as _machine_design_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    machine_design_intermediate as _machine_design_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    machines_advanced as _machines_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import machines_basics as _machines_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    machines_intermediate as _machines_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    manufacturing_processes_advanced as _manufacturing_processes_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    manufacturing_processes_basics as _manufacturing_processes_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    manufacturing_processes_intermediate as _manufacturing_processes_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    materials_science_advanced as _materials_science_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    materials_science_basics as _materials_science_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    materials_science_intermediate as _materials_science_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import math_advanced as _math_advanced
from cyberdyne_backend.application.courses.seed_quizzes import math_basics as _math_basics
from cyberdyne_backend.application.courses.seed_quizzes import math_complex as _math_complex
from cyberdyne_backend.application.courses.seed_quizzes import math_discrete as _math_discrete
from cyberdyne_backend.application.courses.seed_quizzes import math_fourier as _math_fourier
from cyberdyne_backend.application.courses.seed_quizzes import math_information as _math_information
from cyberdyne_backend.application.courses.seed_quizzes import (
    math_intermediate as _math_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    math_life_sciences_advanced as _math_life_sciences_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    math_life_sciences_basics as _math_life_sciences_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    math_life_sciences_intermediate as _math_life_sciences_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import math_matrices as _math_matrices
from cyberdyne_backend.application.courses.seed_quizzes import math_numerical as _math_numerical
from cyberdyne_backend.application.courses.seed_quizzes import (
    math_optimization as _math_optimization,
)
from cyberdyne_backend.application.courses.seed_quizzes import math_probability as _math_probability
from cyberdyne_backend.application.courses.seed_quizzes import matlab_basics as _matlab_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    mechanical_vibrations_advanced as _mechanical_vibrations_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    mechanical_vibrations_basics as _mechanical_vibrations_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    mechanical_vibrations_intermediate as _mechanical_vibrations_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    mechanics_of_materials_advanced as _mechanics_of_materials_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    mechanics_of_materials_basics as _mechanics_of_materials_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    mechanics_of_materials_intermediate as _mechanics_of_materials_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    mechatronics_advanced as _mechatronics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    mechatronics_basics as _mechatronics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    mechatronics_intermediate as _mechatronics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    medicinal_chemistry_advanced as _medicinal_chemistry_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    medicinal_chemistry_basics as _medicinal_chemistry_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    medicinal_chemistry_intermediate as _medicinal_chemistry_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    microbiology_advanced as _microbiology_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    microbiology_basics as _microbiology_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    microbiology_intermediate as _microbiology_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    microwave_advanced as _microwave_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import microwave_basics as _microwave_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    microwave_intermediate as _microwave_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ml_for_engineering_advanced as _ml_for_engineering_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ml_for_engineering_basics as _ml_for_engineering_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ml_for_engineering_intermediate as _ml_for_engineering_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ml_life_sciences_advanced as _ml_life_sciences_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ml_life_sciences_basics as _ml_life_sciences_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ml_life_sciences_intermediate as _ml_life_sciences_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    molecular_biology_advanced as _molecular_biology_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    molecular_biology_basics as _molecular_biology_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    molecular_biology_intermediate as _molecular_biology_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    molecular_dynamics_advanced as _molecular_dynamics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    molecular_dynamics_basics as _molecular_dynamics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    molecular_dynamics_intermediate as _molecular_dynamics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    molecular_modeling_advanced as _molecular_modeling_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    molecular_modeling_basics as _molecular_modeling_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    molecular_modeling_intermediate as _molecular_modeling_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import mongodb as _mongodb
from cyberdyne_backend.application.courses.seed_quizzes import (
    multibody_dynamics_advanced as _multibody_dynamics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    multibody_dynamics_basics as _multibody_dynamics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    multibody_dynamics_intermediate as _multibody_dynamics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ngs_analysis_advanced as _ngs_analysis_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ngs_analysis_basics as _ngs_analysis_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    ngs_analysis_intermediate as _ngs_analysis_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    organic_chemistry_advanced as _organic_chemistry_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    organic_chemistry_basics as _organic_chemistry_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    organic_chemistry_intermediate as _organic_chemistry_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import pcb_advanced as _pcb_advanced
from cyberdyne_backend.application.courses.seed_quizzes import pcb_basics as _pcb_basics
from cyberdyne_backend.application.courses.seed_quizzes import pcb_intermediate as _pcb_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import (
    pharmacology_advanced as _pharmacology_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    pharmacology_basics as _pharmacology_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    pharmacology_intermediate as _pharmacology_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    photonics_advanced as _photonics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import photonics_basics as _photonics_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    photonics_intermediate as _photonics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    phylogenetics_advanced as _phylogenetics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    phylogenetics_basics as _phylogenetics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    phylogenetics_intermediate as _phylogenetics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    physical_chemistry_advanced as _physical_chemistry_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    physical_chemistry_basics as _physical_chemistry_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    physical_chemistry_intermediate as _physical_chemistry_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import physics_basics as _physics_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    physics_intermediate as _physics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    physics_life_sciences_advanced as _physics_life_sciences_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    physics_life_sciences_basics as _physics_life_sciences_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    physics_life_sciences_intermediate as _physics_life_sciences_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    physics_quadrotor_dynamics as _physics_quadrotor_dynamics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    physiology_advanced as _physiology_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    physiology_basics as _physiology_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    physiology_intermediate as _physiology_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import postgresql as _postgresql
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_electronics_advanced as _power_electronics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_electronics_basics as _power_electronics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_electronics_intermediate as _power_electronics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_protection_advanced as _power_protection_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_protection_basics as _power_protection_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_protection_intermediate as _power_protection_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_systems_advanced as _power_systems_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_systems_basics as _power_systems_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    power_systems_intermediate as _power_systems_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    prob_stats_python_advanced as _prob_stats_python_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    prob_stats_python_basics as _prob_stats_python_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    prob_stats_python_intermediate as _prob_stats_python_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    programming_biology_python_advanced as _programming_biology_python_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    programming_biology_python_basics as _programming_biology_python_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    programming_biology_python_intermediate as _programming_biology_python_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    protein_ligand_binding_advanced as _protein_ligand_binding_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    protein_ligand_binding_basics as _protein_ligand_binding_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    protein_ligand_binding_intermediate as _protein_ligand_binding_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    protein_science_advanced as _protein_science_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    protein_science_basics as _protein_science_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    protein_science_intermediate as _protein_science_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    protein_structure_prediction_advanced as _protein_structure_prediction_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    protein_structure_prediction_basics as _protein_structure_prediction_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    protein_structure_prediction_intermediate as _protein_structure_prediction_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    proteomics_metabolomics_advanced as _proteomics_metabolomics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    proteomics_metabolomics_basics as _proteomics_metabolomics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    proteomics_metabolomics_intermediate as _proteomics_metabolomics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import python_course as _python_course
from cyberdyne_backend.application.courses.seed_quizzes import (
    qsar_modeling_advanced as _qsar_modeling_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    qsar_modeling_basics as _qsar_modeling_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    qsar_modeling_intermediate as _qsar_modeling_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    r_data_analysis_advanced as _r_data_analysis_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    r_data_analysis_basics as _r_data_analysis_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    r_data_analysis_intermediate as _r_data_analysis_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import radar_advanced as _radar_advanced
from cyberdyne_backend.application.courses.seed_quizzes import radar_basics as _radar_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    radar_intermediate as _radar_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import rails_advanced as _rails_advanced
from cyberdyne_backend.application.courses.seed_quizzes import rails_basics as _rails_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    rails_intermediate as _rails_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    renewable_ev_advanced as _renewable_ev_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    renewable_ev_basics as _renewable_ev_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    renewable_ev_intermediate as _renewable_ev_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    reproducible_research_advanced as _reproducible_research_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    reproducible_research_basics as _reproducible_research_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    reproducible_research_intermediate as _reproducible_research_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    rf_comms_advanced as _rf_comms_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import rf_comms_basics as _rf_comms_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    rf_comms_intermediate as _rf_comms_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import rfic_advanced as _rfic_advanced
from cyberdyne_backend.application.courses.seed_quizzes import rfic_basics as _rfic_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    rfic_intermediate as _rfic_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    robot_manipulators_advanced as _robot_manipulators_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    robot_manipulators_basics as _robot_manipulators_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    robot_manipulators_intermediate as _robot_manipulators_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    robotics_advanced as _robotics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import robotics_basics as _robotics_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    robotics_intermediate as _robotics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import rust_basics as _rust_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    rust_intermediate as _rust_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    scientific_computing_advanced as _scientific_computing_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    scientific_computing_basics as _scientific_computing_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    scientific_computing_intermediate as _scientific_computing_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    semiconductor_advanced as _semiconductor_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    semiconductor_basics as _semiconductor_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    semiconductor_intermediate as _semiconductor_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import sensors_advanced as _sensors_advanced
from cyberdyne_backend.application.courses.seed_quizzes import sensors_basics as _sensors_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    sensors_intermediate as _sensors_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    sequence_analysis_advanced as _sequence_analysis_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    sequence_analysis_basics as _sequence_analysis_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    sequence_analysis_intermediate as _sequence_analysis_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import signals_advanced as _signals_advanced
from cyberdyne_backend.application.courses.seed_quizzes import signals_basics as _signals_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    signals_intermediate as _signals_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    single_cell_omics_advanced as _single_cell_omics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    single_cell_omics_basics as _single_cell_omics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    single_cell_omics_intermediate as _single_cell_omics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    smart_grid_advanced as _smart_grid_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    smart_grid_basics as _smart_grid_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    smart_grid_intermediate as _smart_grid_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    software_architecture_advanced as _software_architecture_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    software_architecture_basics as _software_architecture_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    software_architecture_intermediate as _software_architecture_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    software_quality_advanced as _software_quality_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    software_quality_basics as _software_quality_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    software_quality_intermediate as _software_quality_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import sql_basics as _sql_basics
from cyberdyne_backend.application.courses.seed_quizzes import sql_intermediate as _sql_intermediate
from cyberdyne_backend.application.courses.seed_quizzes import statinf_advanced as _statinf_advanced
from cyberdyne_backend.application.courses.seed_quizzes import statinf_basics as _statinf_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    statinf_intermediate as _statinf_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    stochastic_processes_advanced as _stochastic_processes_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    stochastic_processes_basics as _stochastic_processes_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    stochastic_processes_intermediate as _stochastic_processes_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    structural_biology_advanced as _structural_biology_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    structural_biology_basics as _structural_biology_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    structural_biology_intermediate as _structural_biology_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import swift_basics as _swift_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    swift_intermediate as _swift_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    systems_biology_advanced as _systems_biology_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    systems_biology_basics as _systems_biology_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    systems_biology_intermediate as _systems_biology_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    sysverilog_advanced as _sysverilog_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    sysverilog_basics as _sysverilog_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    sysverilog_intermediate as _sysverilog_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    target_identification_advanced as _target_identification_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    target_identification_basics as _target_identification_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    target_identification_intermediate as _target_identification_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    technical_english_advanced as _technical_english_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    technical_english_basics as _technical_english_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    technical_english_intermediate as _technical_english_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    terraform_advanced as _terraform_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import terraform_basics as _terraform_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    terraform_intermediate as _terraform_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    topology_optimization_advanced as _topology_optimization_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    topology_optimization_basics as _topology_optimization_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    topology_optimization_intermediate as _topology_optimization_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    transcriptomics_advanced as _transcriptomics_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    transcriptomics_basics as _transcriptomics_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    transcriptomics_intermediate as _transcriptomics_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    typescript_basics as _typescript_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    typescript_intermediate as _typescript_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    vectorcalc_advanced as _vectorcalc_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    vectorcalc_basics as _vectorcalc_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    vectorcalc_intermediate as _vectorcalc_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import vlsi_advanced as _vlsi_advanced
from cyberdyne_backend.application.courses.seed_quizzes import vlsi_basics as _vlsi_basics
from cyberdyne_backend.application.courses.seed_quizzes import (
    vlsi_intermediate as _vlsi_intermediate,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    wireless_comms_advanced as _wireless_comms_advanced,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    wireless_comms_basics as _wireless_comms_basics,
)
from cyberdyne_backend.application.courses.seed_quizzes import (
    wireless_comms_intermediate as _wireless_comms_intermediate,
)
from cyberdyne_backend.application.courses.seed_types import CourseQuiz

QUIZ_REGISTRY: dict[str, CourseQuiz] = {
    "actuators-motion-systems-basics": _actuators_motion_systems_basics.QUIZ,
    "actuators-motion-systems-intermediate": _actuators_motion_systems_intermediate.QUIZ,
    "actuators-motion-systems-advanced": _actuators_motion_systems_advanced.QUIZ,
    "ai-organic-shapes-basics": _ai_organic_shapes_basics.QUIZ,
    "ai-organic-shapes-intermediate": _ai_organic_shapes_intermediate.QUIZ,
    "ai-organic-shapes-advanced": _ai_organic_shapes_advanced.QUIZ,
    "cad-cae-parametric-basics": _cad_cae_parametric_basics.QUIZ,
    "cad-cae-parametric-intermediate": _cad_cae_parametric_intermediate.QUIZ,
    "cad-cae-parametric-advanced": _cad_cae_parametric_advanced.QUIZ,
    "capstone-generative-mechanical-design-basics": _capstone_generative_mechanical_design_basics.QUIZ,
    "capstone-generative-mechanical-design-intermediate": _capstone_generative_mechanical_design_intermediate.QUIZ,
    "capstone-generative-mechanical-design-advanced": _capstone_generative_mechanical_design_advanced.QUIZ,
    "computational-fluid-dynamics-basics": _computational_fluid_dynamics_basics.QUIZ,
    "computational-fluid-dynamics-intermediate": _computational_fluid_dynamics_intermediate.QUIZ,
    "computational-fluid-dynamics-advanced": _computational_fluid_dynamics_advanced.QUIZ,
    "design-optimization-basics": _design_optimization_basics.QUIZ,
    "design-optimization-intermediate": _design_optimization_intermediate.QUIZ,
    "design-optimization-advanced": _design_optimization_advanced.QUIZ,
    "finite-element-analysis-basics": _finite_element_analysis_basics.QUIZ,
    "finite-element-analysis-intermediate": _finite_element_analysis_intermediate.QUIZ,
    "finite-element-analysis-advanced": _finite_element_analysis_advanced.QUIZ,
    "generative-design-basics": _generative_design_basics.QUIZ,
    "generative-design-intermediate": _generative_design_intermediate.QUIZ,
    "generative-design-advanced": _generative_design_advanced.QUIZ,
    "hydraulics-pneumatics-basics": _hydraulics_pneumatics_basics.QUIZ,
    "hydraulics-pneumatics-intermediate": _hydraulics_pneumatics_intermediate.QUIZ,
    "hydraulics-pneumatics-advanced": _hydraulics_pneumatics_advanced.QUIZ,
    "kinematics-of-machinery-basics": _kinematics_of_machinery_basics.QUIZ,
    "kinematics-of-machinery-intermediate": _kinematics_of_machinery_intermediate.QUIZ,
    "kinematics-of-machinery-advanced": _kinematics_of_machinery_advanced.QUIZ,
    "machine-design-basics": _machine_design_basics.QUIZ,
    "machine-design-intermediate": _machine_design_intermediate.QUIZ,
    "machine-design-advanced": _machine_design_advanced.QUIZ,
    "mechanical-vibrations-basics": _mechanical_vibrations_basics.QUIZ,
    "mechanical-vibrations-intermediate": _mechanical_vibrations_intermediate.QUIZ,
    "mechanical-vibrations-advanced": _mechanical_vibrations_advanced.QUIZ,
    "mechatronics-basics": _mechatronics_basics.QUIZ,
    "mechatronics-intermediate": _mechatronics_intermediate.QUIZ,
    "mechatronics-advanced": _mechatronics_advanced.QUIZ,
    "ml-for-engineering-basics": _ml_for_engineering_basics.QUIZ,
    "ml-for-engineering-intermediate": _ml_for_engineering_intermediate.QUIZ,
    "ml-for-engineering-advanced": _ml_for_engineering_advanced.QUIZ,
    "multibody-dynamics-basics": _multibody_dynamics_basics.QUIZ,
    "multibody-dynamics-intermediate": _multibody_dynamics_intermediate.QUIZ,
    "multibody-dynamics-advanced": _multibody_dynamics_advanced.QUIZ,
    "robot-manipulators-basics": _robot_manipulators_basics.QUIZ,
    "robot-manipulators-intermediate": _robot_manipulators_intermediate.QUIZ,
    "robot-manipulators-advanced": _robot_manipulators_advanced.QUIZ,
    "topology-optimization-basics": _topology_optimization_basics.QUIZ,
    "topology-optimization-intermediate": _topology_optimization_intermediate.QUIZ,
    "topology-optimization-advanced": _topology_optimization_advanced.QUIZ,
    "additive-manufacturing-basics": _additive_manufacturing_basics.QUIZ,
    "additive-manufacturing-intermediate": _additive_manufacturing_intermediate.QUIZ,
    "additive-manufacturing-advanced": _additive_manufacturing_advanced.QUIZ,
    "engineering-dynamics-basics": _engineering_dynamics_basics.QUIZ,
    "engineering-dynamics-intermediate": _engineering_dynamics_intermediate.QUIZ,
    "engineering-dynamics-advanced": _engineering_dynamics_advanced.QUIZ,
    "engineering-graphics-cad-basics": _engineering_graphics_cad_basics.QUIZ,
    "engineering-graphics-cad-intermediate": _engineering_graphics_cad_intermediate.QUIZ,
    "engineering-graphics-cad-advanced": _engineering_graphics_cad_advanced.QUIZ,
    "engineering-statics-basics": _engineering_statics_basics.QUIZ,
    "engineering-statics-intermediate": _engineering_statics_intermediate.QUIZ,
    "engineering-statics-advanced": _engineering_statics_advanced.QUIZ,
    "engineering-thermodynamics-basics": _engineering_thermodynamics_basics.QUIZ,
    "engineering-thermodynamics-intermediate": _engineering_thermodynamics_intermediate.QUIZ,
    "engineering-thermodynamics-advanced": _engineering_thermodynamics_advanced.QUIZ,
    "fluid-mechanics-basics": _fluid_mechanics_basics.QUIZ,
    "fluid-mechanics-intermediate": _fluid_mechanics_intermediate.QUIZ,
    "fluid-mechanics-advanced": _fluid_mechanics_advanced.QUIZ,
    "heat-transfer-basics": _heat_transfer_basics.QUIZ,
    "heat-transfer-intermediate": _heat_transfer_intermediate.QUIZ,
    "heat-transfer-advanced": _heat_transfer_advanced.QUIZ,
    "manufacturing-processes-basics": _manufacturing_processes_basics.QUIZ,
    "manufacturing-processes-intermediate": _manufacturing_processes_intermediate.QUIZ,
    "manufacturing-processes-advanced": _manufacturing_processes_advanced.QUIZ,
    "materials-science-basics": _materials_science_basics.QUIZ,
    "materials-science-intermediate": _materials_science_intermediate.QUIZ,
    "materials-science-advanced": _materials_science_advanced.QUIZ,
    "mechanics-of-materials-basics": _mechanics_of_materials_basics.QUIZ,
    "mechanics-of-materials-intermediate": _mechanics_of_materials_intermediate.QUIZ,
    "mechanics-of-materials-advanced": _mechanics_of_materials_advanced.QUIZ,
    "admet-prediction-basics": _admet_prediction_basics.QUIZ,
    "admet-prediction-intermediate": _admet_prediction_intermediate.QUIZ,
    "admet-prediction-advanced": _admet_prediction_advanced.QUIZ,
    "ai-drug-discovery-basics": _ai_drug_discovery_basics.QUIZ,
    "ai-drug-discovery-intermediate": _ai_drug_discovery_intermediate.QUIZ,
    "ai-drug-discovery-advanced": _ai_drug_discovery_advanced.QUIZ,
    "capstone-ai-drug-design-basics": _capstone_ai_drug_design_basics.QUIZ,
    "capstone-ai-drug-design-intermediate": _capstone_ai_drug_design_intermediate.QUIZ,
    "capstone-ai-drug-design-advanced": _capstone_ai_drug_design_advanced.QUIZ,
    "cheminformatics-basics": _cheminformatics_basics.QUIZ,
    "cheminformatics-intermediate": _cheminformatics_intermediate.QUIZ,
    "cheminformatics-advanced": _cheminformatics_advanced.QUIZ,
    "computer-aided-drug-design-basics": _computer_aided_drug_design_basics.QUIZ,
    "computer-aided-drug-design-intermediate": _computer_aided_drug_design_intermediate.QUIZ,
    "computer-aided-drug-design-advanced": _computer_aided_drug_design_advanced.QUIZ,
    "deep-learning-biology-basics": _deep_learning_biology_basics.QUIZ,
    "deep-learning-biology-intermediate": _deep_learning_biology_intermediate.QUIZ,
    "deep-learning-biology-advanced": _deep_learning_biology_advanced.QUIZ,
    "docking-virtual-screening-basics": _docking_virtual_screening_basics.QUIZ,
    "docking-virtual-screening-intermediate": _docking_virtual_screening_intermediate.QUIZ,
    "docking-virtual-screening-advanced": _docking_virtual_screening_advanced.QUIZ,
    "drug-development-regulatory-basics": _drug_development_regulatory_basics.QUIZ,
    "drug-development-regulatory-intermediate": _drug_development_regulatory_intermediate.QUIZ,
    "drug-development-regulatory-advanced": _drug_development_regulatory_advanced.QUIZ,
    "generative-molecular-design-basics": _generative_molecular_design_basics.QUIZ,
    "generative-molecular-design-intermediate": _generative_molecular_design_intermediate.QUIZ,
    "generative-molecular-design-advanced": _generative_molecular_design_advanced.QUIZ,
    "medicinal-chemistry-basics": _medicinal_chemistry_basics.QUIZ,
    "medicinal-chemistry-intermediate": _medicinal_chemistry_intermediate.QUIZ,
    "medicinal-chemistry-advanced": _medicinal_chemistry_advanced.QUIZ,
    "ml-life-sciences-basics": _ml_life_sciences_basics.QUIZ,
    "ml-life-sciences-intermediate": _ml_life_sciences_intermediate.QUIZ,
    "ml-life-sciences-advanced": _ml_life_sciences_advanced.QUIZ,
    "molecular-dynamics-basics": _molecular_dynamics_basics.QUIZ,
    "molecular-dynamics-intermediate": _molecular_dynamics_intermediate.QUIZ,
    "molecular-dynamics-advanced": _molecular_dynamics_advanced.QUIZ,
    "molecular-modeling-basics": _molecular_modeling_basics.QUIZ,
    "molecular-modeling-intermediate": _molecular_modeling_intermediate.QUIZ,
    "molecular-modeling-advanced": _molecular_modeling_advanced.QUIZ,
    "ngs-analysis-basics": _ngs_analysis_basics.QUIZ,
    "ngs-analysis-intermediate": _ngs_analysis_intermediate.QUIZ,
    "ngs-analysis-advanced": _ngs_analysis_advanced.QUIZ,
    "phylogenetics-basics": _phylogenetics_basics.QUIZ,
    "phylogenetics-intermediate": _phylogenetics_intermediate.QUIZ,
    "phylogenetics-advanced": _phylogenetics_advanced.QUIZ,
    "protein-ligand-binding-basics": _protein_ligand_binding_basics.QUIZ,
    "protein-ligand-binding-intermediate": _protein_ligand_binding_intermediate.QUIZ,
    "protein-ligand-binding-advanced": _protein_ligand_binding_advanced.QUIZ,
    "protein-structure-prediction-basics": _protein_structure_prediction_basics.QUIZ,
    "protein-structure-prediction-intermediate": _protein_structure_prediction_intermediate.QUIZ,
    "protein-structure-prediction-advanced": _protein_structure_prediction_advanced.QUIZ,
    "proteomics-metabolomics-basics": _proteomics_metabolomics_basics.QUIZ,
    "proteomics-metabolomics-intermediate": _proteomics_metabolomics_intermediate.QUIZ,
    "proteomics-metabolomics-advanced": _proteomics_metabolomics_advanced.QUIZ,
    "qsar-modeling-basics": _qsar_modeling_basics.QUIZ,
    "qsar-modeling-intermediate": _qsar_modeling_intermediate.QUIZ,
    "qsar-modeling-advanced": _qsar_modeling_advanced.QUIZ,
    "reproducible-research-basics": _reproducible_research_basics.QUIZ,
    "reproducible-research-intermediate": _reproducible_research_intermediate.QUIZ,
    "reproducible-research-advanced": _reproducible_research_advanced.QUIZ,
    "sequence-analysis-basics": _sequence_analysis_basics.QUIZ,
    "sequence-analysis-intermediate": _sequence_analysis_intermediate.QUIZ,
    "sequence-analysis-advanced": _sequence_analysis_advanced.QUIZ,
    "single-cell-omics-basics": _single_cell_omics_basics.QUIZ,
    "single-cell-omics-intermediate": _single_cell_omics_intermediate.QUIZ,
    "single-cell-omics-advanced": _single_cell_omics_advanced.QUIZ,
    "systems-biology-basics": _systems_biology_basics.QUIZ,
    "systems-biology-intermediate": _systems_biology_intermediate.QUIZ,
    "systems-biology-advanced": _systems_biology_advanced.QUIZ,
    "target-identification-basics": _target_identification_basics.QUIZ,
    "target-identification-intermediate": _target_identification_intermediate.QUIZ,
    "target-identification-advanced": _target_identification_advanced.QUIZ,
    "transcriptomics-basics": _transcriptomics_basics.QUIZ,
    "transcriptomics-intermediate": _transcriptomics_intermediate.QUIZ,
    "transcriptomics-advanced": _transcriptomics_advanced.QUIZ,
    "analytical-chemistry-basics": _analytical_chemistry_basics.QUIZ,
    "analytical-chemistry-intermediate": _analytical_chemistry_intermediate.QUIZ,
    "analytical-chemistry-advanced": _analytical_chemistry_advanced.QUIZ,
    "bio-databases-basics": _bio_databases_basics.QUIZ,
    "bio-databases-intermediate": _bio_databases_intermediate.QUIZ,
    "bio-databases-advanced": _bio_databases_advanced.QUIZ,
    "biochemistry-basics": _biochemistry_basics.QUIZ,
    "biochemistry-intermediate": _biochemistry_intermediate.QUIZ,
    "biochemistry-advanced": _biochemistry_advanced.QUIZ,
    "bioinformatics-basics": _bioinformatics_basics.QUIZ,
    "bioinformatics-intermediate": _bioinformatics_intermediate.QUIZ,
    "bioinformatics-advanced": _bioinformatics_advanced.QUIZ,
    "biostatistics-basics": _biostatistics_basics.QUIZ,
    "biostatistics-intermediate": _biostatistics_intermediate.QUIZ,
    "biostatistics-advanced": _biostatistics_advanced.QUIZ,
    "cell-biology-basics": _cell_biology_basics.QUIZ,
    "cell-biology-intermediate": _cell_biology_intermediate.QUIZ,
    "cell-biology-advanced": _cell_biology_advanced.QUIZ,
    "data-visualization-bio-basics": _data_visualization_bio_basics.QUIZ,
    "data-visualization-bio-intermediate": _data_visualization_bio_intermediate.QUIZ,
    "data-visualization-bio-advanced": _data_visualization_bio_advanced.QUIZ,
    "evolution-ecology-basics": _evolution_ecology_basics.QUIZ,
    "evolution-ecology-intermediate": _evolution_ecology_intermediate.QUIZ,
    "evolution-ecology-advanced": _evolution_ecology_advanced.QUIZ,
    "general-chemistry-basics": _general_chemistry_basics.QUIZ,
    "general-chemistry-intermediate": _general_chemistry_intermediate.QUIZ,
    "general-chemistry-advanced": _general_chemistry_advanced.QUIZ,
    "genetics-basics": _genetics_basics.QUIZ,
    "genetics-intermediate": _genetics_intermediate.QUIZ,
    "genetics-advanced": _genetics_advanced.QUIZ,
    "genomics-basics": _genomics_basics.QUIZ,
    "genomics-intermediate": _genomics_intermediate.QUIZ,
    "genomics-advanced": _genomics_advanced.QUIZ,
    "immunology-basics": _immunology_basics.QUIZ,
    "immunology-intermediate": _immunology_intermediate.QUIZ,
    "immunology-advanced": _immunology_advanced.QUIZ,
    "math-life-sciences-basics": _math_life_sciences_basics.QUIZ,
    "math-life-sciences-intermediate": _math_life_sciences_intermediate.QUIZ,
    "math-life-sciences-advanced": _math_life_sciences_advanced.QUIZ,
    "microbiology-basics": _microbiology_basics.QUIZ,
    "microbiology-intermediate": _microbiology_intermediate.QUIZ,
    "microbiology-advanced": _microbiology_advanced.QUIZ,
    "molecular-biology-basics": _molecular_biology_basics.QUIZ,
    "molecular-biology-intermediate": _molecular_biology_intermediate.QUIZ,
    "molecular-biology-advanced": _molecular_biology_advanced.QUIZ,
    "organic-chemistry-basics": _organic_chemistry_basics.QUIZ,
    "organic-chemistry-intermediate": _organic_chemistry_intermediate.QUIZ,
    "organic-chemistry-advanced": _organic_chemistry_advanced.QUIZ,
    "pharmacology-basics": _pharmacology_basics.QUIZ,
    "pharmacology-intermediate": _pharmacology_intermediate.QUIZ,
    "pharmacology-advanced": _pharmacology_advanced.QUIZ,
    "physical-chemistry-basics": _physical_chemistry_basics.QUIZ,
    "physical-chemistry-intermediate": _physical_chemistry_intermediate.QUIZ,
    "physical-chemistry-advanced": _physical_chemistry_advanced.QUIZ,
    "physics-life-sciences-basics": _physics_life_sciences_basics.QUIZ,
    "physics-life-sciences-intermediate": _physics_life_sciences_intermediate.QUIZ,
    "physics-life-sciences-advanced": _physics_life_sciences_advanced.QUIZ,
    "physiology-basics": _physiology_basics.QUIZ,
    "physiology-intermediate": _physiology_intermediate.QUIZ,
    "physiology-advanced": _physiology_advanced.QUIZ,
    "programming-biology-python-basics": _programming_biology_python_basics.QUIZ,
    "programming-biology-python-intermediate": _programming_biology_python_intermediate.QUIZ,
    "programming-biology-python-advanced": _programming_biology_python_advanced.QUIZ,
    "protein-science-basics": _protein_science_basics.QUIZ,
    "protein-science-intermediate": _protein_science_intermediate.QUIZ,
    "protein-science-advanced": _protein_science_advanced.QUIZ,
    "r-data-analysis-basics": _r_data_analysis_basics.QUIZ,
    "r-data-analysis-intermediate": _r_data_analysis_intermediate.QUIZ,
    "r-data-analysis-advanced": _r_data_analysis_advanced.QUIZ,
    "scientific-computing-basics": _scientific_computing_basics.QUIZ,
    "scientific-computing-intermediate": _scientific_computing_intermediate.QUIZ,
    "scientific-computing-advanced": _scientific_computing_advanced.QUIZ,
    "structural-biology-basics": _structural_biology_basics.QUIZ,
    "structural-biology-intermediate": _structural_biology_intermediate.QUIZ,
    "structural-biology-advanced": _structural_biology_advanced.QUIZ,
    "advanced-control-advanced": _advanced_control_advanced.QUIZ,
    "advanced-control-basics": _advanced_control_basics.QUIZ,
    "advanced-control-intermediate": _advanced_control_intermediate.QUIZ,
    "electric-drives-advanced": _electric_drives_advanced.QUIZ,
    "electric-drives-basics": _electric_drives_basics.QUIZ,
    "electric-drives-intermediate": _electric_drives_intermediate.QUIZ,
    "high-voltage-advanced": _high_voltage_advanced.QUIZ,
    "high-voltage-basics": _high_voltage_basics.QUIZ,
    "high-voltage-intermediate": _high_voltage_intermediate.QUIZ,
    "power-protection-advanced": _power_protection_advanced.QUIZ,
    "power-protection-basics": _power_protection_basics.QUIZ,
    "power-protection-intermediate": _power_protection_intermediate.QUIZ,
    "renewable-ev-advanced": _renewable_ev_advanced.QUIZ,
    "renewable-ev-basics": _renewable_ev_basics.QUIZ,
    "renewable-ev-intermediate": _renewable_ev_intermediate.QUIZ,
    "smart-grid-advanced": _smart_grid_advanced.QUIZ,
    "smart-grid-basics": _smart_grid_basics.QUIZ,
    "smart-grid-intermediate": _smart_grid_intermediate.QUIZ,
    "adaptive-dsp-advanced": _adaptive_dsp_advanced.QUIZ,
    "adaptive-dsp-basics": _adaptive_dsp_basics.QUIZ,
    "adaptive-dsp-intermediate": _adaptive_dsp_intermediate.QUIZ,
    "analog-comms-advanced": _analog_comms_advanced.QUIZ,
    "analog-comms-basics": _analog_comms_basics.QUIZ,
    "analog-comms-intermediate": _analog_comms_intermediate.QUIZ,
    "audio-processing-advanced": _audio_processing_advanced.QUIZ,
    "audio-processing-basics": _audio_processing_basics.QUIZ,
    "audio-processing-intermediate": _audio_processing_intermediate.QUIZ,
    "coding-theory-advanced": _coding_theory_advanced.QUIZ,
    "coding-theory-basics": _coding_theory_basics.QUIZ,
    "coding-theory-intermediate": _coding_theory_intermediate.QUIZ,
    "fiber-optics-advanced": _fiber_optics_advanced.QUIZ,
    "fiber-optics-basics": _fiber_optics_basics.QUIZ,
    "fiber-optics-intermediate": _fiber_optics_intermediate.QUIZ,
    "image-processing-advanced": _image_processing_advanced.QUIZ,
    "image-processing-basics": _image_processing_basics.QUIZ,
    "image-processing-intermediate": _image_processing_intermediate.QUIZ,
    "radar-advanced": _radar_advanced.QUIZ,
    "radar-basics": _radar_basics.QUIZ,
    "radar-intermediate": _radar_intermediate.QUIZ,
    "stochastic-processes-advanced": _stochastic_processes_advanced.QUIZ,
    "stochastic-processes-basics": _stochastic_processes_basics.QUIZ,
    "stochastic-processes-intermediate": _stochastic_processes_intermediate.QUIZ,
    "wireless-comms-advanced": _wireless_comms_advanced.QUIZ,
    "wireless-comms-basics": _wireless_comms_basics.QUIZ,
    "wireless-comms-intermediate": _wireless_comms_intermediate.QUIZ,
    "algorithms-advanced": _algorithms_advanced.QUIZ,
    "algorithms-basics": _algorithms_basics.QUIZ,
    "algorithms-intermediate": _algorithms_intermediate.QUIZ,
    "algorithms-logic-computing": _algorithms_logic_computing.QUIZ,
    "analog-ic-advanced": _analog_ic_advanced.QUIZ,
    "analog-ic-basics": _analog_ic_basics.QUIZ,
    "analog-ic-intermediate": _analog_ic_intermediate.QUIZ,
    "ansible-advanced": _ansible_advanced.QUIZ,
    "ansible-basics": _ansible_basics.QUIZ,
    "ansible-intermediate": _ansible_intermediate.QUIZ,
    "battery-advanced": _battery_advanced.QUIZ,
    "battery-basics": _battery_basics.QUIZ,
    "battery-intermediate": _battery_intermediate.QUIZ,
    "blockchain-basics": _blockchain_basics.QUIZ,
    "blockchain-beyond-basics": _blockchain_beyond_basics.QUIZ,
    "c-basics": _c_basics.QUIZ,
    "c-intermediate": _c_intermediate.QUIZ,
    "circuit-analysis-advanced": _circuit_analysis_advanced.QUIZ,
    "circuit-analysis-basics": _circuit_analysis_basics.QUIZ,
    "circuit-analysis-intermediate": _circuit_analysis_intermediate.QUIZ,
    "comparch-advanced": _comparch_advanced.QUIZ,
    "comparch-basics": _comparch_basics.QUIZ,
    "comparch-intermediate": _comparch_intermediate.QUIZ,
    "computational-thinking-advanced": _computational_thinking_advanced.QUIZ,
    "computational-thinking-basics": _computational_thinking_basics.QUIZ,
    "computational-thinking-intermediate": _computational_thinking_intermediate.QUIZ,
    "control-advanced": _control_advanced.QUIZ,
    "control-basics": _control_basics.QUIZ,
    "control-intermediate": _control_intermediate.QUIZ,
    "cpp-basics": _cpp_basics.QUIZ,
    "cpp-intermediate": _cpp_intermediate.QUIZ,
    "csharp-advanced": _csharp_advanced.QUIZ,
    "csharp-basics": _csharp_basics.QUIZ,
    "csharp-intermediate": _csharp_intermediate.QUIZ,
    "data-converters-advanced": _data_converters_advanced.QUIZ,
    "data-converters-basics": _data_converters_basics.QUIZ,
    "data-converters-intermediate": _data_converters_intermediate.QUIZ,
    "digital-comms-advanced": _digital_comms_advanced.QUIZ,
    "digital-comms-basics": _digital_comms_basics.QUIZ,
    "digital-comms-intermediate": _digital_comms_intermediate.QUIZ,
    "digital-logic-advanced": _digital_logic_advanced.QUIZ,
    "digital-logic-basics": _digital_logic_basics.QUIZ,
    "digital-logic-intermediate": _digital_logic_intermediate.QUIZ,
    "django-advanced": _django_advanced.QUIZ,
    "django-basics": _django_basics.QUIZ,
    "django-intermediate": _django_intermediate.QUIZ,
    "docker-advanced": _docker_advanced.QUIZ,
    "docker-basics": _docker_basics.QUIZ,
    "docker-intermediate": _docker_intermediate.QUIZ,
    "dsp-advanced": _dsp_advanced.QUIZ,
    "dsp-basics": _dsp_basics.QUIZ,
    "dsp-intermediate": _dsp_intermediate.QUIZ,
    "electromagnetics-advanced": _electromagnetics_advanced.QUIZ,
    "electromagnetics-basics": _electromagnetics_basics.QUIZ,
    "electromagnetics-intermediate": _electromagnetics_intermediate.QUIZ,
    "electronics-advanced": _electronics_advanced.QUIZ,
    "electronics-basics": _electronics_basics.QUIZ,
    "electronics-intermediate": _electronics_intermediate.QUIZ,
    "embedded-advanced": _embedded_advanced.QUIZ,
    "embedded-basics": _embedded_basics.QUIZ,
    "embedded-intermediate": _embedded_intermediate.QUIZ,
    "english-br-advanced": _english_brazil_advanced.QUIZ,
    "english-br-basics": _english_brazil_basics.QUIZ,
    "english-br-intermediate": _english_brazil_intermediate.QUIZ,
    "filter-design-advanced": _filter_design_advanced.QUIZ,
    "filter-design-basics": _filter_design_basics.QUIZ,
    "filter-design-intermediate": _filter_design_intermediate.QUIZ,
    "fpga-advanced": _fpga_advanced.QUIZ,
    "fpga-basics": _fpga_basics.QUIZ,
    "fpga-intermediate": _fpga_intermediate.QUIZ,
    "go-basics": _go_basics.QUIZ,
    "go-intermediate": _go_intermediate.QUIZ,
    "javascript-basics": _javascript_basics.QUIZ,
    "javascript-intermediate": _javascript_intermediate.QUIZ,
    "kubernetes-advanced": _kubernetes_advanced.QUIZ,
    "kubernetes-basics": _kubernetes_basics.QUIZ,
    "kubernetes-intermediate": _kubernetes_intermediate.QUIZ,
    "machines-advanced": _machines_advanced.QUIZ,
    "machines-basics": _machines_basics.QUIZ,
    "machines-intermediate": _machines_intermediate.QUIZ,
    "math-advanced": _math_advanced.QUIZ,
    "math-basics": _math_basics.QUIZ,
    "math-complex": _math_complex.QUIZ,
    "math-discrete": _math_discrete.QUIZ,
    "math-fourier": _math_fourier.QUIZ,
    "math-information": _math_information.QUIZ,
    "math-intermediate": _math_intermediate.QUIZ,
    "math-matrices": _math_matrices.QUIZ,
    "math-numerical": _math_numerical.QUIZ,
    "math-optimization": _math_optimization.QUIZ,
    "math-probability": _math_probability.QUIZ,
    "matlab-basics": _matlab_basics.QUIZ,
    "microwave-advanced": _microwave_advanced.QUIZ,
    "microwave-basics": _microwave_basics.QUIZ,
    "microwave-intermediate": _microwave_intermediate.QUIZ,
    "mongodb": _mongodb.QUIZ,
    "pcb-advanced": _pcb_advanced.QUIZ,
    "pcb-basics": _pcb_basics.QUIZ,
    "pcb-intermediate": _pcb_intermediate.QUIZ,
    "photonics-advanced": _photonics_advanced.QUIZ,
    "photonics-basics": _photonics_basics.QUIZ,
    "photonics-intermediate": _photonics_intermediate.QUIZ,
    "physics-basics": _physics_basics.QUIZ,
    "physics-intermediate": _physics_intermediate.QUIZ,
    "physics-quadrotor-dynamics": _physics_quadrotor_dynamics.QUIZ,
    "postgresql": _postgresql.QUIZ,
    "power-electronics-advanced": _power_electronics_advanced.QUIZ,
    "power-electronics-basics": _power_electronics_basics.QUIZ,
    "power-electronics-intermediate": _power_electronics_intermediate.QUIZ,
    "power-systems-advanced": _power_systems_advanced.QUIZ,
    "power-systems-basics": _power_systems_basics.QUIZ,
    "power-systems-intermediate": _power_systems_intermediate.QUIZ,
    "prob-stats-python-advanced": _prob_stats_python_advanced.QUIZ,
    "prob-stats-python-basics": _prob_stats_python_basics.QUIZ,
    "prob-stats-python-intermediate": _prob_stats_python_intermediate.QUIZ,
    "python-course": _python_course.QUIZ,
    "rails-advanced": _rails_advanced.QUIZ,
    "rails-basics": _rails_basics.QUIZ,
    "rails-intermediate": _rails_intermediate.QUIZ,
    "rfic-advanced": _rfic_advanced.QUIZ,
    "rfic-basics": _rfic_basics.QUIZ,
    "rfic-intermediate": _rfic_intermediate.QUIZ,
    "rf-comms-advanced": _rf_comms_advanced.QUIZ,
    "rf-comms-basics": _rf_comms_basics.QUIZ,
    "rf-comms-intermediate": _rf_comms_intermediate.QUIZ,
    "robotics-advanced": _robotics_advanced.QUIZ,
    "robotics-basics": _robotics_basics.QUIZ,
    "robotics-intermediate": _robotics_intermediate.QUIZ,
    "rust-basics": _rust_basics.QUIZ,
    "rust-intermediate": _rust_intermediate.QUIZ,
    "semiconductor-advanced": _semiconductor_advanced.QUIZ,
    "semiconductor-basics": _semiconductor_basics.QUIZ,
    "semiconductor-intermediate": _semiconductor_intermediate.QUIZ,
    "sensors-advanced": _sensors_advanced.QUIZ,
    "sensors-basics": _sensors_basics.QUIZ,
    "sensors-intermediate": _sensors_intermediate.QUIZ,
    "signals-advanced": _signals_advanced.QUIZ,
    "signals-basics": _signals_basics.QUIZ,
    "signals-intermediate": _signals_intermediate.QUIZ,
    "software-architecture-advanced": _software_architecture_advanced.QUIZ,
    "software-architecture-basics": _software_architecture_basics.QUIZ,
    "software-architecture-intermediate": _software_architecture_intermediate.QUIZ,
    "software-quality-advanced": _software_quality_advanced.QUIZ,
    "software-quality-basics": _software_quality_basics.QUIZ,
    "software-quality-intermediate": _software_quality_intermediate.QUIZ,
    "sql-basics": _sql_basics.QUIZ,
    "sql-intermediate": _sql_intermediate.QUIZ,
    "statinf-advanced": _statinf_advanced.QUIZ,
    "statinf-basics": _statinf_basics.QUIZ,
    "statinf-intermediate": _statinf_intermediate.QUIZ,
    "swift-basics": _swift_basics.QUIZ,
    "swift-intermediate": _swift_intermediate.QUIZ,
    "sysverilog-advanced": _sysverilog_advanced.QUIZ,
    "sysverilog-basics": _sysverilog_basics.QUIZ,
    "sysverilog-intermediate": _sysverilog_intermediate.QUIZ,
    "technical-english-advanced": _technical_english_advanced.QUIZ,
    "technical-english-basics": _technical_english_basics.QUIZ,
    "technical-english-intermediate": _technical_english_intermediate.QUIZ,
    "terraform-advanced": _terraform_advanced.QUIZ,
    "terraform-basics": _terraform_basics.QUIZ,
    "terraform-intermediate": _terraform_intermediate.QUIZ,
    "typescript-basics": _typescript_basics.QUIZ,
    "typescript-intermediate": _typescript_intermediate.QUIZ,
    "vectorcalc-advanced": _vectorcalc_advanced.QUIZ,
    "vectorcalc-basics": _vectorcalc_basics.QUIZ,
    "vectorcalc-intermediate": _vectorcalc_intermediate.QUIZ,
    "vlsi-advanced": _vlsi_advanced.QUIZ,
    "vlsi-basics": _vlsi_basics.QUIZ,
    "vlsi-intermediate": _vlsi_intermediate.QUIZ,
}

__all__ = ["QUIZ_REGISTRY"]
